all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 89.232.188.12
        web2:
          ansible_host: 89.232.188.130
        web3:
          ansible_host: 178.154.244.134
      vars:
        ansible_user: sergei
        ansible_ssh_private_key_file: ~/.ssh/id_rsa