- hosts: all
  gather_facts: no
  vars:
    server_messages:
      web1: "Hello from web1 server!"
      web2: "Greetings from web2 server!"
      web3: "Greetings from web3 server!"

  tasks:


    - community.docker.docker_network:
        name: devops-example


    - community.docker.docker_container:
        name: app
        image: "sergei3333/my-app-devops:{{ version }}"

        restart_policy: always

        state: started
        networks:
          - name: devops-example

        ports:

        env:
          NODE_ENV: production
          SERVER_MESSAGE: "{{ server_messages[inventory_hostname] }}"
        image_name_mismatch: recreate


    - community.docker.docker_container:
        name: caddy
        image: "sergei3333/my-app-devops-caddy:{{ version }}"
        restart_policy: always
        state: started
        networks:
          - name: devops-example
        ports:
          - 80:80
          - 443:443
