- hosts: all
  gather_facts: no
  tasks:


    - community.docker.docker_container:
        name: app
        image: "sergei3333/my-app-devops:{{ version }}"

        restart_policy: always

        state: started

        ports:
          - 3000:3000
        env:
          NODE_ENV: production
        image_name_mismatch: recreate
